export var recipes = [
  {
    image: "../Assets/Images/not_foundimage.png",
    reviewRate: 4.8,
    reviewCount: 1250,
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "meat",
    title: "Classic Beef Burger",
    description:
      "Juicy homemade beef patties with fresh vegetables and special sauce.",
    ingredients: [
      "500g ground beef",
      "4 burger buns",
      "Cheddar cheese",
      "Lettuce",
      "Tomato",
    ],
    instructions: [
      "Shape the beef into patties",
      "Grill for 5 minutes each side",
      "Assemble the burger",
    ],
    nutrition: {
      caloriesValue: 550,
      proteinValue: 35,
      carbohydratesValue: 40,
      fatValue: 30,
      fiberValue: 2,
      sodium: 800,
    },
    chiefTips: ["Don't overmix the meat", "Toast the buns for extra crunch"],
  },
  {
    image: "caesar-salad.webp",
    reviewRate: 4.5,
    reviewCount: 890,
    cookTime: 50,
    prepTime: 20,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Chicken Caesar Salad",
    description:
      "Crispy romaine lettuce topped with grilled chicken and parmesan.",
    ingredients: [
      "2 chicken breasts",
      "Romaine lettuce",
      "Croutons",
      "Caesar dressing",
      "Parmesan",
    ],
    instructions: [
      "Grill chicken",
      "Chop lettuce",
      "Mix with dressing and croutons",
    ],
    nutrition: {
      caloriesValue: 320,
      proteinValue: 28,
      carbohydratesValue: 12,
      fatValue: 18,
      fiberValue: 4,
      sodium: 650,
    },
    chiefTips: [
      "Use fresh garlic in dressing",
      "Chill the bowl before serving",
    ],
  },
  {
    image: "sushi-rolls.png",
    reviewRate: 4.9,
    reviewCount: 2100,
    cookTime: 20,
    prepTime: 45,
    servings: 3,
    level: "hard",
    type: "seafood",
    title: "Salmon Avocado Sushi",
    description: "Fresh salmon and creamy avocado wrapped in seasoned rice.",
    ingredients: [
      "Sushi rice",
      "Nori sheets",
      "Fresh salmon",
      "Avocado",
      "Rice vinegar",
    ],
    instructions: [
      "Cook rice",
      "Spread rice on nori",
      "Add salmon and avocado",
      "Roll tightly",
    ],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 20,
      carbohydratesValue: 60,
      fatValue: 15,
      fiberValue: 5,
      sodium: 400,
    },
    chiefTips: [
      "Wet your hands to handle rice",
      "Use a very sharp knife to slice",
    ],
  },
  {
    image: "lentil-soup.jpg",
    reviewRate: 4.7,
    reviewCount: 3400,
    cookTime: 40,
    prepTime: 10,
    servings: 6,
    level: "easy",
    type: "vegetarian",
    title: "Red Lentil Soup",
    description: "Warm and comforting traditional middle eastern soup.",
    ingredients: [
      "2 cups red lentils",
      "1 onion",
      "2 carrots",
      "Cumin",
      "Olive oil",
    ],
    instructions: [
      "Sauté onions",
      "Add lentils and water",
      "Boil until soft",
      "Blend until smooth",
    ],
    nutrition: {
      caloriesValue: 180,
      proteinValue: 12,
      carbohydratesValue: 28,
      fatValue: 3,
      fiberValue: 8,
      sodium: 320,
    },
    chiefTips: [
      "Add a squeeze of lemon before serving",
      "Garnish with toasted bread",
    ],
  },
  {
    image: "margherita-pizza.jpg",
    reviewRate: 5.0,
    reviewCount: 5200,
    cookTime: 12,
    prepTime: 120,
    servings: 2,
    level: "medium",
    type: "vegetarian",
    title: "Neapolitan Margherita Pizza",
    description:
      "The classic Italian pizza with tomato, mozzarella, and basil.",
    ingredients: [
      "Pizza dough",
      "San Marzano tomatoes",
      "Fresh mozzarella",
      "Fresh basil",
      "Olive oil",
    ],
    instructions: [
      "Stretch the dough",
      "Spread sauce",
      "Add cheese",
      "Bake at high heat",
    ],
    nutrition: {
      caloriesValue: 600,
      proteinValue: 22,
      carbohydratesValue: 80,
      fatValue: 20,
      fiberValue: 3,
      sodium: 950,
    },
    chiefTips: [
      "Use a pizza stone for a crispy crust",
      "Don't overload with sauce",
    ],
  },
  {
    image: "steak-frites.jpg",
    reviewRate: 4.6,
    reviewCount: 1100,
    cookTime: 15,
    prepTime: 10,
    servings: 1,
    level: "medium",
    type: "meat",
    title: "Ribeye Steak with Fries",
    description: "Perfectly seared ribeye served with golden french fries.",
    ingredients: [
      "300g Ribeye steak",
      "2 potatoes",
      "Butter",
      "Garlic",
      "Rosemary",
    ],
    instructions: [
      "Season steak",
      "Sear in hot pan",
      "Baste with butter",
      "Fry potatoes",
    ],
    nutrition: {
      caloriesValue: 850,
      proteinValue: 55,
      carbohydratesValue: 45,
      fatValue: 50,
      fiberValue: 4,
      sodium: 700,
    },
    chiefTips: [
      "Let steak rest for 5 minutes",
      "Pat the steak dry before searing",
    ],
  },
  {
    image: "thai-green-curry.jpg",
    reviewRate: 4.8,
    reviewCount: 750,
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "poultry",
    title: "Thai Green Chicken Curry",
    description: "A spicy and aromatic curry with coconut milk.",
    ingredients: [
      "Chicken breast",
      "Green curry paste",
      "Coconut milk",
      "Bamboo shoots",
      "Thai basil",
    ],
    instructions: [
      "Fry curry paste",
      "Add chicken",
      "Pour coconut milk",
      "Simmer with vegetables",
    ],
    nutrition: {
      caloriesValue: 420,
      proteinValue: 30,
      carbohydratesValue: 15,
      fatValue: 28,
      fiberValue: 2,
      sodium: 880,
    },
    chiefTips: [
      "Adjust spice with more or less paste",
      "Serve with jasmine rice",
    ],
  },
  {
    image: "grilled-salmon.webp",
    reviewRate: 4.9,
    reviewCount: 1800,
    cookTime: 12,
    prepTime: 5,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Honey Garlic Grilled Salmon",
    description: "Glazed salmon fillets that are sweet, savory, and flaky.",
    ingredients: [
      "2 Salmon fillets",
      "Honey",
      "Soy sauce",
      "Garlic",
      "Lemon juice",
    ],
    instructions: [
      "Mix glaze",
      "Brush on salmon",
      "Grill until cooked through",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 34,
      carbohydratesValue: 12,
      fatValue: 22,
      fiberValue: 0,
      sodium: 540,
    },
    chiefTips: ["Keep the skin on for more flavor", "Don't overcook salmon"],
  },
  {
    image: "falafel-wrap.jpg",
    reviewRate: 4.4,
    reviewCount: 2200,
    cookTime: 20,
    prepTime: 40,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Crispy Falafel Wrap",
    description: "Golden fried falafel with tahini sauce in pita bread.",
    ingredients: ["Chickpeas", "Parsley", "Garlic", "Pita bread", "Tahini"],
    instructions: [
      "Blend chickpeas and herbs",
      "Form balls",
      "Deep fry",
      "Wrap in pita",
    ],
    nutrition: {
      caloriesValue: 480,
      proteinValue: 15,
      carbohydratesValue: 55,
      fatValue: 22,
      fiberValue: 12,
      sodium: 620,
    },
    chiefTips: ["Use dried chickpeas, not canned", "Fry in small batches"],
  },
  {
    image: "beef-tacos.jpg",
    reviewRate: 4.7,
    reviewCount: 1560,
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    level: "easy",
    type: "meat",
    title: "Mexican Beef Tacos",
    description: "Street-style tacos with seasoned beef and fresh salsa.",
    ingredients: ["Ground beef", "Taco shells", "Onion", "Cilantro", "Lime"],
    instructions: [
      "Brown the beef",
      "Season with spices",
      "Fill shells",
      "Add toppings",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 25,
      carbohydratesValue: 30,
      fatValue: 20,
      fiberValue: 5,
      sodium: 740,
    },
    chiefTips: ["Warm the taco shells", "Use fresh lime for acidity"],
  },
  {
    image: "mushroom-risotto.jpg",
    reviewRate: 4.6,
    reviewCount: 920,
    cookTime: 35,
    prepTime: 10,
    servings: 4,
    level: "hard",
    type: "vegetarian",
    title: "Creamy Mushroom Risotto",
    description: "Slow-cooked Italian rice with earthy mushrooms.",
    ingredients: [
      "Arborio rice",
      "Mushrooms",
      "Vegetable stock",
      "White wine",
      "Parmesan",
    ],
    instructions: [
      "Sauté mushrooms",
      "Toast rice",
      "Add stock gradually",
      "Stir constantly",
    ],
    nutrition: {
      caloriesValue: 390,
      proteinValue: 10,
      carbohydratesValue: 52,
      fatValue: 14,
      fiberValue: 3,
      sodium: 580,
    },
    chiefTips: ["Keep the stock hot", "Use a heavy-bottomed pan"],
  },
  {
    image: "pancakes.webp",
    reviewRate: 4.8,
    reviewCount: 4100,
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    level: "easy",
    type: "breakfast",
    title: "Fluffy Buttermilk Pancakes",
    description: "Soft and airy pancakes perfect for a weekend breakfast.",
    ingredients: ["Flour", "Buttermilk", "Eggs", "Baking powder", "Butter"],
    instructions: [
      "Mix dry ingredients",
      "Add wet ingredients",
      "Cook on griddle",
    ],
    nutrition: {
      caloriesValue: 310,
      proteinValue: 8,
      carbohydratesValue: 45,
      fatValue: 10,
      fiberValue: 1,
      sodium: 450,
    },
    chiefTips: ["Don't overmix the batter", "Flip when bubbles appear"],
  },
  {
    image: "shrimp-scampi.jpg",
    reviewRate: 4.7,
    reviewCount: 1300,
    cookTime: 210,
    prepTime: 10,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Garlic Shrimp Scampi",
    description: "Shrimp sautéed in a garlic, butter, and white wine sauce.",
    ingredients: ["Large shrimp", "Garlic", "Lemon", "Parsley", "Butter"],
    instructions: [
      "Sauté garlic",
      "Add shrimp",
      "Deglaze with wine/lemon",
      "Toss with parsley",
    ],
    nutrition: {
      caloriesValue: 280,
      proteinValue: 24,
      carbohydratesValue: 5,
      fatValue: 18,
      fiberValue: 0,
      sodium: 520,
    },
    chiefTips: ["Use wild-caught shrimp", "Serve over linguine"],
  },
  {
    image: "chicken-biryani.jpg",
    reviewRate: 4.9,
    reviewCount: 3800,
    cookTime: 60,
    prepTime: 30,
    servings: 6,
    level: "hard",
    type: "poultry",
    title: "Hyderabadi Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken.",
    ingredients: [
      "Basmati rice",
      "Chicken",
      "Yogurt",
      "Saffron",
      "Fried onions",
    ],
    instructions: [
      "Marinate chicken",
      "Parboil rice",
      "Layer chicken and rice",
      "Steam (Dum)",
    ],
    nutrition: {
      caloriesValue: 620,
      proteinValue: 38,
      carbohydratesValue: 75,
      fatValue: 18,
      fiberValue: 4,
      sodium: 900,
    },
    chiefTips: [
      "Use high-quality long grain rice",
      "Let it rest before opening",
    ],
  },
  {
    image: "greek-salad.jpg",
    reviewRate: 4.5,
    reviewCount: 640,
    cookTime: 0,
    prepTime: 15,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Traditional Greek Salad",
    description: "Fresh cucumbers, tomatoes, olives, and feta cheese.",
    ingredients: [
      "Cucumber",
      "Tomato",
      "Kalamata olives",
      "Feta cheese",
      "Dried oregano",
    ],
    instructions: [
      "Chop vegetables",
      "Add olives and feta",
      "Drizzle with olive oil",
    ],
    nutrition: {
      caloriesValue: 210,
      proteinValue: 6,
      carbohydratesValue: 10,
      fatValue: 16,
      fiberValue: 3,
      sodium: 700,
    },
    chiefTips: [
      "Don't chop the feta, leave it in large blocks",
      "Use extra virgin olive oil",
    ],
  },
  {
    image: "lamb-chops.jpg",
    reviewRate: 4.8,
    reviewCount: 530,
    cookTime: 12,
    prepTime: 20,
    servings: 2,
    level: "medium",
    type: "meat",
    title: "Garlic Rosemary Lamb Chops",
    description: "Tender lamb chops infused with aromatic herbs.",
    ingredients: ["Lamb chops", "Rosemary", "Garlic", "Olive oil", "Butter"],
    instructions: ["Marinate lamb", "Sear in pan", "Baste with garlic butter"],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 32,
      carbohydratesValue: 2,
      fatValue: 35,
      fiberValue: 0,
      sodium: 380,
    },
    chiefTips: [
      "Bring meat to room temperature before cooking",
      "Sear the fat edge first",
    ],
  },
  {
    image: "quinoa-bowl.jpg",
    reviewRate: 4.3,
    reviewCount: 420,
    cookTime: 320,
    prepTime: 15,
    servings: 1,
    level: "easy",
    type: "vegetarian",
    title: "Buddha Quinoa Bowl",
    description: "A healthy mix of quinoa, roasted chickpeas, and tahini.",
    ingredients: [
      "Quinoa",
      "Chickpeas",
      "Spinach",
      "Sweet potato",
      "Tahini sauce",
    ],
    instructions: [
      "Cook quinoa",
      "Roast chickpeas",
      "Assemble bowl",
      "Drizzle sauce",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 14,
      carbohydratesValue: 55,
      fatValue: 12,
      fiberValue: 10,
      sodium: 290,
    },
    chiefTips: ["Massage the kale or spinach", "Meal prep this for lunch"],
  },
  {
    image: "lasagna.jpg",
    reviewRate: 4.9,
    reviewCount: 2900,
    cookTime: 45,
    prepTime: 30,
    servings: 8,
    level: "hard",
    type: "meat",
    title: "Classic Beef Lasagna",
    description: "Layers of pasta, rich meat sauce, and creamy béchamel.",
    ingredients: [
      "Lasagna sheets",
      "Ground beef",
      "Tomato sauce",
      "Milk",
      "Cheese",
    ],
    instructions: [
      "Make meat sauce",
      "Make béchamel",
      "Layer ingredients",
      "Bake",
    ],
    nutrition: {
      caloriesValue: 520,
      proteinValue: 30,
      carbohydratesValue: 40,
      fatValue: 25,
      fiberValue: 2,
      sodium: 850,
    },
    chiefTips: [
      "Let it rest for 15 minutes before cutting",
      "Use mix of mozzarella and parmesan",
    ],
  },
  {
    image: "eggplant-parm.jpg",
    reviewRate: 4.6,
    reviewCount: 780,
    cookTime: 40,
    prepTime: 30,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Eggplant Parmesan",
    description: "Baked eggplant slices layered with cheese and marinara.",
    ingredients: [
      "Eggplant",
      "Marinara sauce",
      "Mozzarella",
      "Breadcrumbs",
      "Egg",
    ],
    instructions: [
      "Bread eggplant",
      "Fry or bake",
      "Layer with sauce/cheese",
      "Bake again",
    ],
    nutrition: {
      caloriesValue: 340,
      proteinValue: 15,
      carbohydratesValue: 28,
      fatValue: 18,
      fiberValue: 7,
      sodium: 600,
    },
    chiefTips: [
      "Salt the eggplant to remove bitterness",
      "Don't use too much oil",
    ],
  },
  {
    image: "pad-thai.jpg",
    reviewRate: 4.7,
    reviewCount: 1950,
    cookTime: 515,
    prepTime: 20,
    servings: 2,
    level: "medium",
    type: "seafood",
    title: "Authentic Shrimp Pad Thai",
    description: "Classic Thai stir-fried rice noodles with shrimp.",
    ingredients: [
      "Rice noodles",
      "Shrimp",
      "Tamarind paste",
      "Peanuts",
      "Bean sprouts",
    ],
    instructions: [
      "Soak noodles",
      "Stir-fry shrimp",
      "Add noodles and sauce",
      "Top with peanuts",
    ],
    nutrition: {
      caloriesValue: 490,
      proteinValue: 24,
      carbohydratesValue: 65,
      fatValue: 15,
      fiberValue: 4,
      sodium: 920,
    },
    chiefTips: [
      "Don't oversoak the noodles",
      "Use palm sugar for authenticity",
    ],
  },
  {
    image: "chicken-wings.jpg",
    reviewRate: 4.8,
    reviewCount: 3100,
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    level: "easy",
    type: "poultry",
    title: "Buffalo Chicken Wings",
    description: "Crispy fried wings tossed in spicy buffalo sauce.",
    ingredients: [
      "1kg Chicken wings",
      "Hot sauce",
      "Butter",
      "Garlic powder",
      "Flour",
    ],
    instructions: ["Coat wings in flour", "Fry until crispy", "Toss in sauce"],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 22,
      carbohydratesValue: 5,
      fatValue: 38,
      fiberValue: 0,
      sodium: 1100,
    },
    chiefTips: [
      "Dry wings thoroughly for crispiness",
      "Use an air fryer for a healthier version",
    ],
  },
  {
    image: "apple-pie.jpg",
    reviewRate: 4.9,
    reviewCount: 1400,
    cookTime: 50,
    prepTime: 40,
    servings: 8,
    level: "hard",
    type: "dessert",
    title: "Classic Apple Pie",
    description: "A flaky buttery crust filled with spiced apples.",
    ingredients: ["Apples", "Pie crust", "Cinnamon", "Sugar", "Butter"],
    instructions: [
      "Make dough",
      "Prepare apple filling",
      "Assemble pie",
      "Bake",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 3,
      carbohydratesValue: 58,
      fatValue: 19,
      fiberValue: 4,
      sodium: 300,
    },
    chiefTips: ["Use a mix of sweet and tart apples", "Keep dough cold"],
  },
  {
    image: "shish-tawook.jpg",
    reviewRate: 4.7,
    reviewCount: 820,
    cookTime: 20,
    prepTime: 120,
    servings: 4,
    level: "medium",
    type: "poultry",
    title: "Grilled Shish Tawook",
    description: "Lebanese-style marinated chicken skewers.",
    ingredients: [
      "Chicken breast",
      "Yogurt",
      "Garlic",
      "Lemon",
      "Tomato paste",
    ],
    instructions: [
      "Marinate chicken",
      "Thread onto skewers",
      "Grill until charred",
    ],
    nutrition: {
      caloriesValue: 320,
      proteinValue: 40,
      carbohydratesValue: 8,
      fatValue: 14,
      fiberValue: 1,
      sodium: 550,
    },
    chiefTips: [
      "Marinate overnight for best flavor",
      "Serve with garlic paste (Toum)",
    ],
  },
  {
    image: "avocado-toast.jpg",
    reviewRate: 4.4,
    reviewCount: 610,
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    level: "easy",
    type: "breakfast",
    title: "Sourdough Avocado Toast",
    description: "Smashed avocado on toasted sourdough with chili flakes.",
    ingredients: [
      "Sourdough bread",
      "Avocado",
      "Red pepper flakes",
      "Lemon",
      "Egg",
    ],
    instructions: [
      "Toast bread",
      "Mash avocado",
      "Spread on toast",
      "Top with poached egg",
    ],
    nutrition: {
      caloriesValue: 290,
      proteinValue: 12,
      carbohydratesValue: 24,
      fatValue: 18,
      fiberValue: 9,
      sodium: 310,
    },
    chiefTips: [
      "Use ripe Hass avocados",
      "A drizzle of balsamic glaze is great",
    ],
  },
  {
    image: "beef-stew.jpg",
    reviewRate: 4.8,
    reviewCount: 1750,
    cookTime: 20,
    prepTime: 20,
    servings: 6,
    level: "medium",
    type: "meat",
    title: "Slow Cooked Beef Stew",
    description: "Tender beef chunks with root vegetables in a rich gravy.",
    ingredients: ["Beef chuck", "Potatoes", "Carrots", "Beef broth", "Onion"],
    instructions: [
      "Sear beef",
      "Add vegetables",
      "Pour broth",
      "Simmer for 2 hours",
    ],
    nutrition: {
      caloriesValue: 420,
      proteinValue: 34,
      carbohydratesValue: 30,
      fatValue: 18,
      fiberValue: 5,
      sodium: 680,
    },
    chiefTips: ["Don't rush the cooking time", "Sear the meat in batches"],
  },
  {
    image:
      "http://googleusercontent.com/image_collection/image_retrieval/9618337179786381369_0",
    reviewRate: 4.9,
    reviewCount: 3200,
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    level: "medium",
    type: "pasta",
    title: "Authentic Spaghetti Carbonara",
    description:
      "Classic Roman pasta made with eggs, pecorino cheese, and crispy guanciale.",
    ingredients: [
      "200g Spaghetti",
      "100g Guanciale",
      "4 large egg yolks",
      "50g Pecorino Romano",
      "Black pepper",
    ],
    instructions: [
      "Boil pasta",
      "Fry guanciale until crisp",
      "Whisk yolks and cheese",
      "Toss everything together off the heat",
    ],
    nutrition: {
      caloriesValue: 580,
      proteinValue: 25,
      carbohydratesValue: 65,
      fatValue: 32,
      fiberValue: 2,
      sodium: 850,
    },
    chiefTips: [
      "Never use cream for authentic carbonara",
      "Use pasta water to create the sauce texture",
    ],
  },
  {
    image:
      "http://googleusercontent.com/image_collection/image_retrieval/17835096852056406846_0",
    reviewRate: 4.8,
    reviewCount: 1540,
    cookTime: 20,
    prepTime: 15,
    servings: 1,
    level: "hard",
    type: "meat",
    title: "Premium Grilled Ribeye",
    description:
      "Perfectly seared ribeye steak served with crispy golden fries and garlic butter.",
    ingredients: [
      "350g Ribeye steak",
      "2 large potatoes",
      "Garlic butter",
      "Fresh rosemary",
      "Sea salt",
    ],
    instructions: [
      "Season steak generously",
      "Sear on high heat",
      "Baste with garlic and rosemary",
      "Deep fry potato wedges",
    ],
    nutrition: {
      caloriesValue: 820,
      proteinValue: 52,
      carbohydratesValue: 40,
      fatValue: 55,
      fiberValue: 3,
      sodium: 920,
    },
    chiefTips: [
      "Let the steak rest for 5-10 minutes before slicing",
      "Ensure the pan is smoking hot before searing",
    ],
  },
  {
    image:
      "http://googleusercontent.com/image_collection/image_retrieval/8321449169607530396_0",
    reviewRate: 4.7,
    reviewCount: 980,
    cookTime: 45,
    prepTime: 20,
    servings: 4,
    level: "hard",
    type: "vegetarian",
    title: "Garden Vegetable Paella",
    description:
      "Traditional Spanish saffron rice loaded with colorful seasonal vegetables.",
    ingredients: [
      "300g Bomba rice",
      "Saffron threads",
      "Artichokes",
      "Red bell peppers",
      "Green beans",
      "Vegetable stock",
    ],
    instructions: [
      "Sauté vegetables",
      "Add rice and saffron",
      "Pour in stock",
      "Cook without stirring to form the crust (socarrat)",
    ],
    nutrition: {
      caloriesValue: 350,
      proteinValue: 8,
      carbohydratesValue: 68,
      fatValue: 6,
      fiberValue: 9,
      sodium: 540,
    },
    chiefTips: [
      "Use a wide, shallow pan for even cooking",
      "Don't stir the rice once it starts simmering",
    ],
  },
  {
    image:
      "http://googleusercontent.com/image_collection/image_retrieval/18429914160034806065_0",
    reviewRate: 4.9,
    reviewCount: 2150,
    cookTime: 120,
    prepTime: 30,
    servings: 2,
    level: "hard",
    type: "soup",
    title: "Rich Beef Shoyu Ramen",
    description:
      "Comforting Japanese noodle soup with a 2-hour slow-cooked beef broth.",
    ingredients: [
      "Ramen noodles",
      "Beef bones",
      "Soy sauce (Shoyu)",
      "Soft-boiled egg",
      "Bamboo shoots",
      "Nori",
    ],
    instructions: [
      "Simmer beef bones for broth",
      "Prepare shoyu tare",
      "Boil noodles",
      "Assemble bowl with toppings",
    ],
    nutrition: {
      caloriesValue: 610,
      proteinValue: 35,
      carbohydratesValue: 70,
      fatValue: 22,
      fiberValue: 4,
      sodium: 1200,
    },
    chiefTips: [
      "The secret is in the 'Tare' sauce",
      "Marinate the eggs overnight for best flavor",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 1250,
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "meat",
    title: "Classic Beef Burger",
    description:
      "Juicy homemade beef patties with fresh vegetables and special sauce.",
    ingredients: [
      "500g ground beef",
      "4 burger buns",
      "Cheddar cheese",
      "Lettuce",
      "Tomato",
    ],
    instructions: [
      "Shape the beef into patties",
      "Grill for 5 minutes each side",
      "Assemble the burger",
    ],
    nutrition: {
      caloriesValue: 550,
      proteinValue: 35,
      carbohydratesValue: 40,
      fatValue: 30,
      fiberValue: 2,
      sodium: 800,
    },
    chiefTips: ["Don't overmix the meat", "Toast the buns for extra crunch"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=500&h=350&fit=crop",
    reviewRate: 4.5,
    reviewCount: 890,
    cookTime: 100,
    prepTime: 20,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Chicken Caesar Salad",
    description:
      "Crispy romaine lettuce topped with grilled chicken and parmesan.",
    ingredients: [
      "2 chicken breasts",
      "Romaine lettuce",
      "Croutons",
      "Caesar dressing",
      "Parmesan",
    ],
    instructions: [
      "Grill chicken",
      "Chop lettuce",
      "Mix with dressing and croutons",
    ],
    nutrition: {
      caloriesValue: 320,
      proteinValue: 28,
      carbohydratesValue: 12,
      fatValue: 18,
      fiberValue: 4,
      sodium: 650,
    },
    chiefTips: [
      "Use fresh garlic in dressing",
      "Chill the bowl before serving",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 2100,
    cookTime: 30,
    prepTime: 45,
    servings: 3,
    level: "hard",
    type: "seafood",
    title: "Salmon Avocado Sushi",
    description: "Fresh salmon and creamy avocado wrapped in seasoned rice.",
    ingredients: [
      "Sushi rice",
      "Nori sheets",
      "Fresh salmon",
      "Avocado",
      "Rice vinegar",
    ],
    instructions: [
      "Cook rice",
      "Spread rice on nori",
      "Add salmon and avocado",
      "Roll tightly",
    ],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 20,
      carbohydratesValue: 60,
      fatValue: 15,
      fiberValue: 5,
      sodium: 400,
    },
    chiefTips: [
      "Wet your hands to handle rice",
      "Use a very sharp knife to slice",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 3400,
    cookTime: 40,
    prepTime: 10,
    servings: 6,
    level: "easy",
    type: "vegetarian",
    title: "Red Lentil Soup",
    description: "Warm and comforting traditional middle eastern soup.",
    ingredients: [
      "2 cups red lentils",
      "1 onion",
      "2 carrots",
      "Cumin",
      "Olive oil",
    ],
    instructions: [
      "Sauté onions",
      "Add lentils and water",
      "Boil until soft",
      "Blend until smooth",
    ],
    nutrition: {
      caloriesValue: 180,
      proteinValue: 12,
      carbohydratesValue: 28,
      fatValue: 3,
      fiberValue: 8,
      sodium: 320,
    },
    chiefTips: [
      "Add a squeeze of lemon before serving",
      "Garnish with toasted bread",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=500&h=350&fit=crop",
    reviewRate: 5.0,
    reviewCount: 5200,
    cookTime: 12,
    prepTime: 120,
    servings: 2,
    level: "medium",
    type: "vegetarian",
    title: "Neapolitan Margherita Pizza",
    description:
      "The classic Italian pizza with tomato, mozzarella, and basil.",
    ingredients: [
      "Pizza dough",
      "San Marzano tomatoes",
      "Fresh mozzarella",
      "Fresh basil",
      "Olive oil",
    ],
    instructions: [
      "Stretch the dough",
      "Spread sauce",
      "Add cheese",
      "Bake at high heat",
    ],
    nutrition: {
      caloriesValue: 600,
      proteinValue: 22,
      carbohydratesValue: 80,
      fatValue: 20,
      fiberValue: 3,
      sodium: 950,
    },
    chiefTips: [
      "Use a pizza stone for a crispy crust",
      "Don't overload with sauce",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=500&h=350&fit=crop",
    reviewRate: 4.6,
    reviewCount: 1100,
    cookTime: 15,
    prepTime: 10,
    servings: 1,
    level: "medium",
    type: "meat",
    title: "Ribeye Steak with Fries",
    description: "Perfectly seared ribeye served with golden french fries.",
    ingredients: [
      "300g Ribeye steak",
      "2 potatoes",
      "Butter",
      "Garlic",
      "Rosemary",
    ],
    instructions: [
      "Season steak",
      "Sear in hot pan",
      "Baste with butter",
      "Fry potatoes",
    ],
    nutrition: {
      caloriesValue: 850,
      proteinValue: 55,
      carbohydratesValue: 45,
      fatValue: 50,
      fiberValue: 4,
      sodium: 700,
    },
    chiefTips: [
      "Let steak rest for 5 minutes",
      "Pat the steak dry before searing",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 750,
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "poultry",
    title: "Thai Green Chicken Curry",
    description: "A spicy and aromatic curry with coconut milk.",
    ingredients: [
      "Chicken breast",
      "Green curry paste",
      "Coconut milk",
      "Bamboo shoots",
      "Thai basil",
    ],
    instructions: [
      "Fry curry paste",
      "Add chicken",
      "Pour coconut milk",
      "Simmer with vegetables",
    ],
    nutrition: {
      caloriesValue: 420,
      proteinValue: 30,
      carbohydratesValue: 15,
      fatValue: 28,
      fiberValue: 2,
      sodium: 880,
    },
    chiefTips: [
      "Adjust spice with more or less paste",
      "Serve with jasmine rice",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 1800,
    cookTime: 12,
    prepTime: 5,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Honey Garlic Grilled Salmon",
    description: "Glazed salmon fillets that are sweet, savory, and flaky.",
    ingredients: [
      "2 Salmon fillets",
      "Honey",
      "Soy sauce",
      "Garlic",
      "Lemon juice",
    ],
    instructions: [
      "Mix glaze",
      "Brush on salmon",
      "Grill until cooked through",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 34,
      carbohydratesValue: 12,
      fatValue: 22,
      fiberValue: 0,
      sodium: 540,
    },
    chiefTips: ["Keep the skin on for more flavor", "Don't overcook salmon"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1593001874117-c99c800e1a79?w=500&h=350&fit=crop",
    reviewRate: 4.4,
    reviewCount: 2200,
    cookTime: 200,
    prepTime: 40,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Crispy Falafel Wrap",
    description: "Golden fried falafel with tahini sauce in pita bread.",
    ingredients: ["Chickpeas", "Parsley", "Garlic", "Pita bread", "Tahini"],
    instructions: [
      "Blend chickpeas and herbs",
      "Form balls",
      "Deep fry",
      "Wrap in pita",
    ],
    nutrition: {
      caloriesValue: 480,
      proteinValue: 15,
      carbohydratesValue: 55,
      fatValue: 22,
      fiberValue: 12,
      sodium: 620,
    },
    chiefTips: ["Use dried chickpeas, not canned", "Fry in small batches"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1560,
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    level: "easy",
    type: "meat",
    title: "Mexican Beef Tacos",
    description: "Street-style tacos with seasoned beef and fresh salsa.",
    ingredients: ["Ground beef", "Taco shells", "Onion", "Cilantro", "Lime"],
    instructions: [
      "Brown the beef",
      "Season with spices",
      "Fill shells",
      "Add toppings",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 25,
      carbohydratesValue: 30,
      fatValue: 20,
      fiberValue: 5,
      sodium: 740,
    },
    chiefTips: ["Warm the taco shells", "Use fresh lime for acidity"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500&h=350&fit=crop",
    reviewRate: 4.6,
    reviewCount: 920,
    cookTime: 35,
    prepTime: 10,
    servings: 4,
    level: "hard",
    type: "vegetarian",
    title: "Creamy Mushroom Risotto",
    description: "Slow-cooked Italian rice with earthy mushrooms.",
    ingredients: [
      "Arborio rice",
      "Mushrooms",
      "Vegetable stock",
      "White wine",
      "Parmesan",
    ],
    instructions: [
      "Sauté mushrooms",
      "Toast rice",
      "Add stock gradually",
      "Stir constantly",
    ],
    nutrition: {
      caloriesValue: 390,
      proteinValue: 10,
      carbohydratesValue: 52,
      fatValue: 14,
      fiberValue: 3,
      sodium: 580,
    },
    chiefTips: ["Keep the stock hot", "Use a heavy-bottomed pan"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 4100,
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    level: "easy",
    type: "breakfast",
    title: "Fluffy Buttermilk Pancakes",
    description: "Soft and airy pancakes perfect for a weekend breakfast.",
    ingredients: ["Flour", "Buttermilk", "Eggs", "Baking powder", "Butter"],
    instructions: [
      "Mix dry ingredients",
      "Add wet ingredients",
      "Cook on griddle",
    ],
    nutrition: {
      caloriesValue: 310,
      proteinValue: 8,
      carbohydratesValue: 45,
      fatValue: 10,
      fiberValue: 1,
      sodium: 450,
    },
    chiefTips: ["Don't overmix the batter", "Flip when bubbles appear"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1300,
    cookTime: 10,
    prepTime: 10,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Garlic Shrimp Scampi",
    description: "Shrimp sautéed in a garlic, butter, and white wine sauce.",
    ingredients: ["Large shrimp", "Garlic", "Lemon", "Parsley", "Butter"],
    instructions: [
      "Sauté garlic",
      "Add shrimp",
      "Deglaze with wine/lemon",
      "Toss with parsley",
    ],
    nutrition: {
      caloriesValue: 280,
      proteinValue: 24,
      carbohydratesValue: 5,
      fatValue: 18,
      fiberValue: 0,
      sodium: 520,
    },
    chiefTips: ["Use wild-caught shrimp", "Serve over linguine"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 3800,
    cookTime: 60,
    prepTime: 30,
    servings: 6,
    level: "hard",
    type: "poultry",
    title: "Hyderabadi Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken.",
    ingredients: [
      "Basmati rice",
      "Chicken",
      "Yogurt",
      "Saffron",
      "Fried onions",
    ],
    instructions: [
      "Marinate chicken",
      "Parboil rice",
      "Layer chicken and rice",
      "Steam (Dum)",
    ],
    nutrition: {
      caloriesValue: 620,
      proteinValue: 38,
      carbohydratesValue: 75,
      fatValue: 18,
      fiberValue: 4,
      sodium: 900,
    },
    chiefTips: [
      "Use high-quality long grain rice",
      "Let it rest before opening",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&h=350&fit=crop",
    reviewRate: 4.5,
    reviewCount: 640,
    cookTime: 0,
    prepTime: 15,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Traditional Greek Salad",
    description: "Fresh cucumbers, tomatoes, olives, and feta cheese.",
    ingredients: [
      "Cucumber",
      "Tomato",
      "Kalamata olives",
      "Feta cheese",
      "Dried oregano",
    ],
    instructions: [
      "Chop vegetables",
      "Add olives and feta",
      "Drizzle with olive oil",
    ],
    nutrition: {
      caloriesValue: 210,
      proteinValue: 6,
      carbohydratesValue: 10,
      fatValue: 16,
      fiberValue: 3,
      sodium: 700,
    },
    chiefTips: [
      "Don't chop the feta, leave it in large blocks",
      "Use extra virgin olive oil",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1547641965-6f3b3da35c47?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 530,
    cookTime: 12,
    prepTime: 20,
    servings: 2,
    level: "medium",
    type: "meat",
    title: "Garlic Rosemary Lamb Chops",
    description: "Tender lamb chops infused with aromatic herbs.",
    ingredients: ["Lamb chops", "Rosemary", "Garlic", "Olive oil", "Butter"],
    instructions: ["Marinate lamb", "Sear in pan", "Baste with garlic butter"],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 32,
      carbohydratesValue: 2,
      fatValue: 35,
      fiberValue: 0,
      sodium: 380,
    },
    chiefTips: [
      "Bring meat to room temperature before cooking",
      "Sear the fat edge first",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=350&fit=crop",
    reviewRate: 4.3,
    reviewCount: 420,
    cookTime: 20,
    prepTime: 15,
    servings: 1,
    level: "easy",
    type: "vegetarian",
    title: "Buddha Quinoa Bowl",
    description: "A healthy mix of quinoa, roasted chickpeas, and tahini.",
    ingredients: [
      "Quinoa",
      "Chickpeas",
      "Spinach",
      "Sweet potato",
      "Tahini sauce",
    ],
    instructions: [
      "Cook quinoa",
      "Roast chickpeas",
      "Assemble bowl",
      "Drizzle sauce",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 14,
      carbohydratesValue: 55,
      fatValue: 12,
      fiberValue: 10,
      sodium: 290,
    },
    chiefTips: ["Massage the kale or spinach", "Meal prep this for lunch"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1574894709923-1bc42b7b6f8c?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 2900,
    cookTime: 45,
    prepTime: 30,
    servings: 8,
    level: "hard",
    type: "meat",
    title: "Classic Beef Lasagna",
    description: "Layers of pasta, rich meat sauce, and creamy béchamel.",
    ingredients: [
      "Lasagna sheets",
      "Ground beef",
      "Tomato sauce",
      "Milk",
      "Cheese",
    ],
    instructions: [
      "Make meat sauce",
      "Make béchamel",
      "Layer ingredients",
      "Bake",
    ],
    nutrition: {
      caloriesValue: 520,
      proteinValue: 30,
      carbohydratesValue: 40,
      fatValue: 25,
      fiberValue: 2,
      sodium: 850,
    },
    chiefTips: [
      "Let it rest for 15 minutes before cutting",
      "Use mix of mozzarella and parmesan",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1581151927997-2d959118dde2?w=500&h=350&fit=crop",
    reviewRate: 4.6,
    reviewCount: 780,
    cookTime: 40,
    prepTime: 30,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Eggplant Parmesan",
    description: "Baked eggplant slices layered with cheese and marinara.",
    ingredients: [
      "Eggplant",
      "Marinara sauce",
      "Mozzarella",
      "Breadcrumbs",
      "Egg",
    ],
    instructions: [
      "Bread eggplant",
      "Fry or bake",
      "Layer with sauce/cheese",
      "Bake again",
    ],
    nutrition: {
      caloriesValue: 340,
      proteinValue: 15,
      carbohydratesValue: 28,
      fatValue: 18,
      fiberValue: 7,
      sodium: 600,
    },
    chiefTips: [
      "Salt the eggplant to remove bitterness",
      "Don't use too much oil",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1950,
    cookTime: 15,
    prepTime: 20,
    servings: 2,
    level: "medium",
    type: "seafood",
    title: "Authentic Shrimp Pad Thai",
    description: "Classic Thai stir-fried rice noodles with shrimp.",
    ingredients: [
      "Rice noodles",
      "Shrimp",
      "Tamarind paste",
      "Peanuts",
      "Bean sprouts",
    ],
    instructions: [
      "Soak noodles",
      "Stir-fry shrimp",
      "Add noodles and sauce",
      "Top with peanuts",
    ],
    nutrition: {
      caloriesValue: 490,
      proteinValue: 24,
      carbohydratesValue: 65,
      fatValue: 15,
      fiberValue: 4,
      sodium: 920,
    },
    chiefTips: [
      "Don't oversoak the noodles",
      "Use palm sugar for authenticity",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 3100,
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    level: "easy",
    type: "poultry",
    title: "Buffalo Chicken Wings",
    description: "Crispy fried wings tossed in spicy buffalo sauce.",
    ingredients: [
      "1kg Chicken wings",
      "Hot sauce",
      "Butter",
      "Garlic powder",
      "Flour",
    ],
    instructions: ["Coat wings in flour", "Fry until crispy", "Toss in sauce"],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 22,
      carbohydratesValue: 5,
      fatValue: 38,
      fiberValue: 0,
      sodium: 1100,
    },
    chiefTips: [
      "Dry wings thoroughly for crispiness",
      "Use an air fryer for a healthier version",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1510618932816-ced4dc0b7302?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 1400,
    cookTime: 50,
    prepTime: 40,
    servings: 8,
    level: "hard",
    type: "dessert",
    title: "Classic Apple Pie",
    description: "A flaky buttery crust filled with spiced apples.",
    ingredients: ["Apples", "Pie crust", "Cinnamon", "Sugar", "Butter"],
    instructions: [
      "Make dough",
      "Prepare apple filling",
      "Assemble pie",
      "Bake",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 3,
      carbohydratesValue: 58,
      fatValue: 19,
      fiberValue: 4,
      sodium: 300,
    },
    chiefTips: ["Use a mix of sweet and tart apples", "Keep dough cold"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.8,
    reviewCount: 2150,
    cookTime: 10,
    prepTime: 15,
    servings: 1,
    level: "easy",
    type: "vegetarian",
    title: "Healthy Quinoa Salad",
    description: "A refreshing blend of quinoa, fresh parsley, and lemon zest.",
    ingredients: [
      "1 cup quinoa",
      "Cucumber",
      "Cherry tomatoes",
      "Lemon juice",
      "Olive oil",
    ],
    instructions: ["Cook quinoa", "Chop vegetables", "Mix with dressing"],
    nutrition: {
      caloriesValue: 320,
      proteinValue: 12,
      carbohydratesValue: 45,
      fatValue: 10,
      fiberValue: 8,
      sodium: 150,
    },
    chiefTips: [
      "Rinse quinoa before cooking to remove bitterness",
      "Add feta for extra saltiness",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.6,
    reviewCount: 980,
    cookTime: 0,
    prepTime: 20,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Greek Buddha Bowl",
    description: "Nutritious bowl with chickpeas, olives, and hummus.",
    ingredients: [
      "Chickpeas",
      "Kalamata olives",
      "Hummus",
      "Spinach",
      "Red onion",
    ],
    instructions: [
      "Place spinach at base",
      "Arrange toppings in sections",
      "Drizzle with tahini",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 15,
      carbohydratesValue: 50,
      fatValue: 18,
      fiberValue: 12,
      sodium: 600,
    },
    chiefTips: [
      "Use homemade hummus if possible",
      "Store leftovers separately",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 5.0,
    reviewCount: 5430,
    cookTime: 15,
    prepTime: 120,
    servings: 4,
    level: "medium",
    type: "pizza",
    title: "Artisan Pepperoni Pizza",
    description: "Thin crust pizza with spicy pepperoni and honey drizzle.",
    ingredients: [
      "Pizza dough",
      "Mozzarella",
      "Pepperoni",
      "Honey",
      "Tomato sauce",
    ],
    instructions: [
      "Stretch dough",
      "Apply sauce and cheese",
      "Bake at 250°C",
      "Drizzle honey",
    ],
    nutrition: {
      caloriesValue: 780,
      proteinValue: 32,
      carbohydratesValue: 85,
      fatValue: 35,
      fiberValue: 3,
      sodium: 1100,
    },
    chiefTips: [
      "High heat is the secret to a crispy crust",
      "Use fresh mozzarella for best melt",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1567620905732-2d1ec7bb7445?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.9,
    reviewCount: 3200,
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    level: "easy",
    type: "breakfast",
    title: "Berry Fluffy Pancakes",
    description: "Thick pancakes topped with organic maple syrup and berries.",
    ingredients: [
      "2 cups flour",
      "2 eggs",
      "Milk",
      "Blueberries",
      "Maple syrup",
    ],
    instructions: [
      "Mix batter",
      "Heat pan with butter",
      "Cook until bubbles form",
      "Flip",
    ],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 10,
      carbohydratesValue: 65,
      fatValue: 12,
      fiberValue: 4,
      sodium: 400,
    },
    chiefTips: [
      "Don't overmix the batter for fluffier texture",
      "Use a cast iron skillet",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1800,
    cookTime: 45,
    prepTime: 30,
    servings: 8,
    level: "hard",
    type: "dessert",
    title: "Strawberry Cheesecake",
    description:
      "Classic New York style cheesecake with fresh strawberry glaze.",
    ingredients: [
      "Cream cheese",
      "Graham crackers",
      "Sugar",
      "Strawberries",
      "Butter",
    ],
    instructions: [
      "Make crust",
      "Beat cheese and sugar",
      "Bake in water bath",
      "Chill for 6 hours",
    ],
    nutrition: {
      caloriesValue: 550,
      proteinValue: 8,
      carbohydratesValue: 48,
      fatValue: 38,
      fiberValue: 2,
      sodium: 320,
    },
    chiefTips: [
      "All ingredients must be at room temperature",
      "Don't open the oven while baking",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.5,
    reviewCount: 1200,
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    level: "easy",
    type: "breakfast",
    title: "Avocado Egg Toast",
    description: "Multigrain bread with mashed avocado and a soft poached egg.",
    ingredients: ["Sourdough", "1 Avocado", "1 Egg", "Chili flakes", "Lemon"],
    instructions: [
      "Toast bread",
      "Mash avocado with lemon",
      "Poach egg",
      "Assemble",
    ],
    nutrition: {
      caloriesValue: 310,
      proteinValue: 14,
      carbohydratesValue: 22,
      fatValue: 19,
      fiberValue: 10,
      sodium: 280,
    },
    chiefTips: [
      "Add a drop of vinegar to water for perfect poached eggs",
      "Season with sea salt",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.4,
    reviewCount: 850,
    cookTime: 15,
    prepTime: 15,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Pan-Seared Salmon",
    description: "Fresh salmon fillet with roasted asparagus and lemon.",
    ingredients: ["2 Salmon fillets", "Asparagus", "Garlic", "Lemon", "Butter"],
    instructions: [
      "Season salmon",
      "Sear skin-side down",
      "Roast asparagus with garlic",
      "Finish with lemon butter",
    ],
    nutrition: {
      caloriesValue: 420,
      proteinValue: 38,
      carbohydratesValue: 8,
      fatValue: 28,
      fiberValue: 3,
      sodium: 450,
    },
    chiefTips: [
      "Pat salmon dry for crispy skin",
      "Don't overcook—medium is best",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.9,
    reviewCount: 2900,
    cookTime: 120,
    prepTime: 40,
    servings: 6,
    level: "hard",
    type: "meat",
    title: "Traditional Beef Lasagna",
    description: "Deep layers of pasta, Bolognese sauce, and creamy Bechamel.",
    ingredients: [
      "Lasagna sheets",
      "Ground beef",
      "Tomato puree",
      "Milk",
      "Parmesan",
    ],
    instructions: [
      "Slow cook meat sauce",
      "Make white sauce",
      "Layer ingredients",
      "Bake until golden",
    ],
    nutrition: {
      caloriesValue: 650,
      proteinValue: 40,
      carbohydratesValue: 42,
      fatValue: 36,
      fiberValue: 3,
      sodium: 890,
    },
    chiefTips: [
      "Let the lasagna rest for 20 mins before slicing",
      "Use high-quality parmesan",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1473093226795-af9932fe5856?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.6,
    reviewCount: 1100,
    cookTime: 12,
    prepTime: 10,
    servings: 2,
    level: "easy",
    type: "pasta",
    title: "Pesto Pasta with Pine Nuts",
    description: "Al dente pasta tossed in fresh basil pesto and toasted nuts.",
    ingredients: [
      "Spaghetti",
      "Fresh basil",
      "Pine nuts",
      "Garlic",
      "Olive oil",
    ],
    instructions: [
      "Boil pasta",
      "Blend pesto ingredients",
      "Toss together",
      "Garnish with nuts",
    ],
    nutrition: {
      caloriesValue: 480,
      proteinValue: 12,
      carbohydratesValue: 55,
      fatValue: 24,
      fiberValue: 4,
      sodium: 310,
    },
    chiefTips: [
      "Toast pine nuts briefly for more flavor",
      "Reserve some pasta water to thin the sauce",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.8,
    reviewCount: 4200,
    cookTime: 15,
    prepTime: 60,
    servings: 4,
    level: "medium",
    type: "pizza",
    title: "Margarita Flatbread",
    description: "Simple and elegant pizza with buffalo mozzarella and basil.",
    ingredients: [
      "Flatbread",
      "Buffalo mozzarella",
      "San Marzano tomatoes",
      "Basil",
      "Oil",
    ],
    instructions: [
      "Top flatbread with tomatoes",
      "Add cheese",
      "Bake for 10 mins",
      "Add fresh basil",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 18,
      carbohydratesValue: 40,
      fatValue: 16,
      fiberValue: 2,
      sodium: 520,
    },
    chiefTips: [
      "Use fresh basil after baking to prevent burning",
      "A drizzle of balsamic glaze is optional",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1563379091339-03b21ef4a4f8?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1340,
    cookTime: 30,
    prepTime: 20,
    servings: 4,
    level: "medium",
    type: "seafood",
    title: "Shrimp Tacos with Lime",
    description: "Zesty shrimp in corn tortillas with cabbage slaw.",
    ingredients: [
      "Large shrimp",
      "Corn tortillas",
      "Red cabbage",
      "Lime juice",
      "Cumin",
    ],
    instructions: [
      "Sauté shrimp with cumin",
      "Mix cabbage with lime",
      "Char tortillas",
      "Assemble",
    ],
    nutrition: {
      caloriesValue: 350,
      proteinValue: 26,
      carbohydratesValue: 32,
      fatValue: 12,
      fiberValue: 6,
      sodium: 680,
    },
    chiefTips: [
      "Use fresh corn tortillas for better taste",
      "Add avocado crema for richness",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.9,
    reviewCount: 2600,
    cookTime: 25,
    prepTime: 15,
    servings: 2,
    level: "medium",
    type: "meat",
    title: "Garlic Butter Ribeye",
    description: "Steakhouse style ribeye cooked in herbs and butter.",
    ingredients: ["Ribeye steak", "Butter", "Garlic", "Thyme", "Black pepper"],
    instructions: [
      "Season steak",
      "Sear in cast iron",
      "Baste with garlic butter",
      "Rest before slicing",
    ],
    nutrition: {
      caloriesValue: 720,
      proteinValue: 48,
      carbohydratesValue: 0,
      fatValue: 58,
      fiberValue: 0,
      sodium: 550,
    },
    chiefTips: [
      "Take steak out of fridge 30 mins before cooking",
      "Use a high smoke point oil first",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.8,
    reviewCount: 3900,
    cookTime: 20,
    prepTime: 15,
    servings: 2,
    level: "medium",
    type: "meat",
    title: "Gourmet Wagyu Burger",
    description: "Double beef patty with truffle mayo and caramelized onions.",
    ingredients: [
      "Wagyu beef",
      "Brioche bun",
      "Truffle mayo",
      "Onions",
      "Swiss cheese",
    ],
    instructions: [
      "Caramelize onions",
      "Grill patties",
      "Assemble burger",
      "Serve with fries",
    ],
    nutrition: {
      caloriesValue: 950,
      proteinValue: 45,
      carbohydratesValue: 35,
      fatValue: 68,
      fiberValue: 2,
      sodium: 1200,
    },
    chiefTips: [
      "Don't press the patties while grilling",
      "Toast the brioche bun with butter",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.3,
    reviewCount: 500,
    cookTime: 25,
    prepTime: 15,
    servings: 3,
    level: "easy",
    type: "vegetarian",
    title: "Roasted Cauliflower Soup",
    description: "Creamy vegan soup made from roasted cauliflower and garlic.",
    ingredients: [
      "Cauliflower",
      "Vegetable stock",
      "Onion",
      "Coconut milk",
      "Garlic",
    ],
    instructions: [
      "Roast cauliflower",
      "Sauté onions",
      "Simmer with stock",
      "Blend until smooth",
    ],
    nutrition: {
      caloriesValue: 210,
      proteinValue: 6,
      carbohydratesValue: 22,
      fatValue: 12,
      fiberValue: 8,
      sodium: 420,
    },
    chiefTips: [
      "Roasted cauliflower adds a nutty flavor",
      "Garnish with chives",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1512058560366-cd24270083cd?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.6,
    reviewCount: 1450,
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    level: "easy",
    type: "poultry",
    title: "Chicken Stir Fry",
    description: "Quick and healthy stir fry with sesame and ginger sauce.",
    ingredients: [
      "Chicken breast",
      "Broccoli",
      "Soy sauce",
      "Ginger",
      "Sesame oil",
    ],
    instructions: [
      "Slice chicken",
      "Stir fry with ginger",
      "Add broccoli",
      "Toss with soy sauce",
    ],
    nutrition: {
      caloriesValue: 340,
      proteinValue: 35,
      carbohydratesValue: 15,
      fatValue: 14,
      fiberValue: 5,
      sodium: 880,
    },
    chiefTips: [
      "Use a very hot pan or wok",
      "Prepare all ingredients before starting",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.7,
    reviewCount: 720,
    cookTime: 35,
    prepTime: 20,
    servings: 4,
    level: "medium",
    type: "poultry",
    title: "Lemon Herb Roasted Chicken",
    description: "Chicken thighs roasted with fresh rosemary and lemon slices.",
    ingredients: [
      "Chicken thighs",
      "Lemons",
      "Rosemary",
      "Potatoes",
      "Olive oil",
    ],
    instructions: [
      "Season chicken",
      "Place in tray with potatoes",
      "Roast at 200°C",
      "Serve with pan juices",
    ],
    nutrition: {
      caloriesValue: 480,
      proteinValue: 32,
      carbohydratesValue: 25,
      fatValue: 28,
      fiberValue: 4,
      sodium: 590,
    },
    chiefTips: [
      "Use bone-in thighs for more flavor",
      "Ensure skin is dry for extra crispness",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.8,
    reviewCount: 2300,
    cookTime: 15,
    prepTime: 15,
    servings: 2,
    level: "medium",
    type: "noodles",
    title: "Spicy Szechuan Noodles",
    description: "Authentic spicy noodles with chili oil and minced pork.",
    ingredients: [
      "Egg noodles",
      "Ground pork",
      "Chili oil",
      "Peanuts",
      "Bok choy",
    ],
    instructions: [
      "Boil noodles",
      "Cook pork with spices",
      "Mix with chili oil sauce",
      "Garnish with peanuts",
    ],
    nutrition: {
      caloriesValue: 580,
      proteinValue: 22,
      carbohydratesValue: 65,
      fatValue: 28,
      fiberValue: 3,
      sodium: 950,
    },
    chiefTips: [
      "Adjust chili oil to your heat preference",
      "Use fresh alkaline noodles if possible",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.5,
    reviewCount: 1100,
    cookTime: 0,
    prepTime: 15,
    servings: 4,
    level: "easy",
    type: "vegetarian",
    title: "Hummus Platter",
    description: "Smooth hummus topped with paprika, pine nuts, and warm pita.",
    ingredients: ["Chickpeas", "Tahini", "Garlic", "Lemon juice", "Pita bread"],
    instructions: [
      "Blend chickpeas and tahini",
      "Add garlic and lemon",
      "Plate and top with oil",
      "Serve with bread",
    ],
    nutrition: {
      caloriesValue: 310,
      proteinValue: 12,
      carbohydratesValue: 42,
      fatValue: 14,
      fiberValue: 10,
      sodium: 480,
    },
    chiefTips: [
      "Remove chickpea skins for extra smooth hummus",
      "Use high-quality tahini",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 5.0,
    reviewCount: 3100,
    cookTime: 20,
    prepTime: 180,
    servings: 5,
    level: "hard",
    type: "meat",
    title: "Middle Eastern Kabab",
    description: "Spiced ground meat skewers grilled over charcoal.",
    ingredients: ["Ground lamb", "Parsley", "Onion", "Allspice", "Sumac"],
    instructions: [
      "Mix meat with herbs",
      "Shape on skewers",
      "Grill until charred",
      "Serve with flatbread",
    ],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 38,
      carbohydratesValue: 5,
      fatValue: 32,
      fiberValue: 1,
      sodium: 620,
    },
    chiefTips: [
      "Keep meat very cold before shaping",
      "Grill over real wood for best flavor",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=1000&auto=format&fit=crop",
    reviewRate: 4.7,
    reviewCount: 890,
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    level: "easy",
    type: "breakfast",
    title: "Shakshuka with Feta",
    description: "Eggs poached in a spicy tomato and bell pepper sauce.",
    ingredients: ["4 Eggs", "Tomatoes", "Bell pepper", "Cumin", "Feta cheese"],
    instructions: [
      "Cook peppers and onions",
      "Add tomatoes and spices",
      "Crack eggs on top",
      "Simmer until set",
    ],
    nutrition: {
      caloriesValue: 280,
      proteinValue: 18,
      carbohydratesValue: 15,
      fatValue: 16,
      fiberValue: 4,
      sodium: 510,
    },
    chiefTips: [
      "Serve with crusty bread for dipping",
      "Don't overcook the yolks",
    ],
  },

  {
    image: "local-carbonara.jpg",
    reviewRate: 4.8,
    reviewCount: 4544,
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    level: "easy",
    type: "pasta",
    title: "Creamy Spaghetti Carbonara",
    description: "Traditional Italian pasta with eggs and guanciale.",
    ingredients: ["Spaghetti", "Guanciale", "Eggs", "Parmesan"],
    instructions: [
      "Boil pasta",
      "Fry meat",
      "Mix egg and cheese",
      "Combine everything",
    ],
    nutrition: {
      caloriesValue: 520,
      proteinValue: 24,
      carbohydratesValue: 60,
      fatValue: 22,
      fiberValue: 2,
      sodium: 700,
    },
    chiefTips: ["Use pasta water for creaminess", "No cream needed"],
  },
  {
    image: "falafel-wrap.png",
    reviewRate: 4.2,
    reviewCount: 310,
    cookTime: 20,
    prepTime: 45,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Crispy Falafel Wrap",
    description: "Homemade falafel with tahini sauce and pickled veggies.",
    ingredients: ["Chickpeas", "Coriander", "Tahini", "Tortilla", "Pickles"],
    instructions: [
      "Blend chickpeas",
      "Fry falafel balls",
      "Wrap with sauce and veg",
    ],
    nutrition: {
      caloriesValue: 460,
      proteinValue: 16,
      carbohydratesValue: 58,
      fatValue: 20,
      fiberValue: 12,
      sodium: 580,
    },
    chiefTips: ["Soak dried chickpeas for 24 hours", "Use fresh herbs"],
  },
  {
    image: "biryani-rice.webp",
    reviewRate: 4.9,
    reviewCount: 2200,
    cookTime: 60,
    prepTime: 30,
    servings: 6,
    level: "hard",
    type: "meat",
    title: "Hyderabadi Chicken Biryani",
    description: "Aromatic basmati rice layered with marinated chicken.",
    ingredients: [
      "Basmati rice",
      "Chicken",
      "Yogurt",
      "Saffron",
      "Fried onions",
    ],
    instructions: ["Marinate chicken", "Parboil rice", "Layer and steam (Dum)"],
    nutrition: {
      caloriesValue: 680,
      proteinValue: 35,
      carbohydratesValue: 85,
      fatValue: 22,
      fiberValue: 5,
      sodium: 900,
    },
    chiefTips: ["Use long grain basmati", "Let it rest before serving"],
  },
  {
    image: "beef-stew-home.jpg",
    reviewRate: 4.7,
    reviewCount: 940,
    cookTime: 120,
    prepTime: 20,
    servings: 4,
    level: "medium",
    type: "meat",
    title: "Slow Cooked Beef Stew",
    description: "Hearty stew with tender beef, carrots, and potatoes.",
    ingredients: ["Beef chuck", "Potatoes", "Carrots", "Onion", "Beef broth"],
    instructions: ["Sear beef", "Add vegetables", "Simmer for 2 hours"],
    nutrition: {
      caloriesValue: 430,
      proteinValue: 32,
      carbohydratesValue: 28,
      fatValue: 20,
      fiberValue: 6,
      sodium: 650,
    },
    chiefTips: ["Sear meat in batches", "Add a splash of red wine for depth"],
  },
  {
    image: "prawn-curry.png",
    reviewRate: 4.6,
    reviewCount: 560,
    cookTime: 20,
    prepTime: 15,
    servings: 3,
    level: "medium",
    type: "seafood",
    title: "Coconut Prawn Curry",
    description: "Tropical spicy curry with prawns and coconut milk.",
    ingredients: [
      "Prawns",
      "Coconut milk",
      "Curry paste",
      "Ginger",
      "Cilantro",
    ],
    instructions: [
      "Fry curry paste",
      "Add prawns",
      "Pour coconut milk",
      "Simmer 5 mins",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 28,
      carbohydratesValue: 12,
      fatValue: 24,
      fiberValue: 2,
      sodium: 720,
    },
    chiefTips: [
      "Don't overcook prawns as they become rubbery",
      "Serve with jasmine rice",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 1250,
    cookTime: 20,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "meat",
    title: "Classic Beef Burger",
    description:
      "Juicy homemade beef patties with fresh vegetables and special sauce.",
    ingredients: [
      "500g ground beef",
      "4 burger buns",
      "Cheddar cheese",
      "Lettuce",
      "Tomato",
    ],
    instructions: [
      "Shape the beef into patties",
      "Grill for 5 minutes each side",
      "Assemble the burger",
    ],
    nutrition: {
      caloriesValue: 550,
      proteinValue: 35,
      carbohydratesValue: 40,
      fatValue: 30,
      fiberValue: 2,
      sodium: 800,
    },
    chiefTips: ["Don't overmix the meat", "Toast the buns for extra crunch"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=500&h=350&fit=crop",
    reviewRate: 4.5,
    reviewCount: 890,
    cookTime: 10,
    prepTime: 20,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Chicken Caesar Salad",
    description:
      "Crispy romaine lettuce topped with grilled chicken and parmesan.",
    ingredients: [
      "2 chicken breasts",
      "Romaine lettuce",
      "Croutons",
      "Caesar dressing",
      "Parmesan",
    ],
    instructions: [
      "Grill chicken",
      "Chop lettuce",
      "Mix with dressing and croutons",
    ],
    nutrition: {
      caloriesValue: 320,
      proteinValue: 28,
      carbohydratesValue: 12,
      fatValue: 18,
      fiberValue: 4,
      sodium: 650,
    },
    chiefTips: [
      "Use fresh garlic in dressing",
      "Chill the bowl before serving",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 2100,
    cookTime: 30,
    prepTime: 45,
    servings: 3,
    level: "hard",
    type: "seafood",
    title: "Salmon Avocado Sushi",
    description: "Fresh salmon and creamy avocado wrapped in seasoned rice.",
    ingredients: [
      "Sushi rice",
      "Nori sheets",
      "Fresh salmon",
      "Avocado",
      "Rice vinegar",
    ],
    instructions: [
      "Cook rice",
      "Spread rice on nori",
      "Add salmon and avocado",
      "Roll tightly",
    ],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 20,
      carbohydratesValue: 60,
      fatValue: 15,
      fiberValue: 5,
      sodium: 400,
    },
    chiefTips: [
      "Wet your hands to handle rice",
      "Use a very sharp knife to slice",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 3400,
    cookTime: 40,
    prepTime: 10,
    servings: 6,
    level: "easy",
    type: "vegetarian",
    title: "Red Lentil Soup",
    description: "Warm and comforting traditional middle eastern soup.",
    ingredients: [
      "2 cups red lentils",
      "1 onion",
      "2 carrots",
      "Cumin",
      "Olive oil",
    ],
    instructions: [
      "Sauté onions",
      "Add lentils and water",
      "Boil until soft",
      "Blend until smooth",
    ],
    nutrition: {
      caloriesValue: 180,
      proteinValue: 12,
      carbohydratesValue: 28,
      fatValue: 3,
      fiberValue: 8,
      sodium: 320,
    },
    chiefTips: [
      "Add a squeeze of lemon before serving",
      "Garnish with toasted bread",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=500&h=350&fit=crop",
    reviewRate: 5.0,
    reviewCount: 5200,
    cookTime: 12,
    prepTime: 120,
    servings: 2,
    level: "medium",
    type: "vegetarian",
    title: "Neapolitan Margherita Pizza",
    description:
      "The classic Italian pizza with tomato, mozzarella, and basil.",
    ingredients: [
      "Pizza dough",
      "San Marzano tomatoes",
      "Fresh mozzarella",
      "Fresh basil",
      "Olive oil",
    ],
    instructions: [
      "Stretch the dough",
      "Spread sauce",
      "Add cheese",
      "Bake at high heat",
    ],
    nutrition: {
      caloriesValue: 600,
      proteinValue: 22,
      carbohydratesValue: 80,
      fatValue: 20,
      fiberValue: 3,
      sodium: 950,
    },
    chiefTips: [
      "Use a pizza stone for a crispy crust",
      "Don't overload with sauce",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=500&h=350&fit=crop",
    reviewRate: 4.6,
    reviewCount: 1100,
    cookTime: 15,
    prepTime: 10,
    servings: 1,
    level: "medium",
    type: "meat",
    title: "Ribeye Steak with Fries",
    description: "Perfectly seared ribeye served with golden french fries.",
    ingredients: [
      "300g Ribeye steak",
      "2 potatoes",
      "Butter",
      "Garlic",
      "Rosemary",
    ],
    instructions: [
      "Season steak",
      "Sear in hot pan",
      "Baste with butter",
      "Fry potatoes",
    ],
    nutrition: {
      caloriesValue: 850,
      proteinValue: 55,
      carbohydratesValue: 45,
      fatValue: 50,
      fiberValue: 4,
      sodium: 700,
    },
    chiefTips: [
      "Let steak rest for 5 minutes",
      "Pat the steak dry before searing",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 750,
    cookTime: 25,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "poultry",
    title: "Thai Green Chicken Curry",
    description: "A spicy and aromatic curry with coconut milk.",
    ingredients: [
      "Chicken breast",
      "Green curry paste",
      "Coconut milk",
      "Bamboo shoots",
      "Thai basil",
    ],
    instructions: [
      "Fry curry paste",
      "Add chicken",
      "Pour coconut milk",
      "Simmer with vegetables",
    ],
    nutrition: {
      caloriesValue: 420,
      proteinValue: 30,
      carbohydratesValue: 15,
      fatValue: 28,
      fiberValue: 2,
      sodium: 880,
    },
    chiefTips: [
      "Adjust spice with more or less paste",
      "Serve with jasmine rice",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 1800,
    cookTime: 12,
    prepTime: 5,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Honey Garlic Grilled Salmon",
    description: "Glazed salmon fillets that are sweet, savory, and flaky.",
    ingredients: [
      "2 Salmon fillets",
      "Honey",
      "Soy sauce",
      "Garlic",
      "Lemon juice",
    ],
    instructions: [
      "Mix glaze",
      "Brush on salmon",
      "Grill until cooked through",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 34,
      carbohydratesValue: 12,
      fatValue: 22,
      fiberValue: 0,
      sodium: 540,
    },
    chiefTips: ["Keep the skin on for more flavor", "Don't overcook salmon"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1593001874117-c99c800e1a79?w=500&h=350&fit=crop",
    reviewRate: 4.4,
    reviewCount: 2200,
    cookTime: 20,
    prepTime: 40,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Crispy Falafel Wrap",
    description: "Golden fried falafel with tahini sauce in pita bread.",
    ingredients: ["Chickpeas", "Parsley", "Garlic", "Pita bread", "Tahini"],
    instructions: [
      "Blend chickpeas and herbs",
      "Form balls",
      "Deep fry",
      "Wrap in pita",
    ],
    nutrition: {
      caloriesValue: 480,
      proteinValue: 15,
      carbohydratesValue: 55,
      fatValue: 22,
      fiberValue: 12,
      sodium: 620,
    },
    chiefTips: ["Use dried chickpeas, not canned", "Fry in small batches"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1560,
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    level: "easy",
    type: "meat",
    title: "Mexican Beef Tacos",
    description: "Street-style tacos with seasoned beef and fresh salsa.",
    ingredients: ["Ground beef", "Taco shells", "Onion", "Cilantro", "Lime"],
    instructions: [
      "Brown the beef",
      "Season with spices",
      "Fill shells",
      "Add toppings",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 25,
      carbohydratesValue: 30,
      fatValue: 20,
      fiberValue: 5,
      sodium: 740,
    },
    chiefTips: ["Warm the taco shells", "Use fresh lime for acidity"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500&h=350&fit=crop",
    reviewRate: 4.6,
    reviewCount: 920,
    cookTime: 35,
    prepTime: 10,
    servings: 4,
    level: "hard",
    type: "vegetarian",
    title: "Creamy Mushroom Risotto",
    description: "Slow-cooked Italian rice with earthy mushrooms.",
    ingredients: [
      "Arborio rice",
      "Mushrooms",
      "Vegetable stock",
      "White wine",
      "Parmesan",
    ],
    instructions: [
      "Sauté mushrooms",
      "Toast rice",
      "Add stock gradually",
      "Stir constantly",
    ],
    nutrition: {
      caloriesValue: 390,
      proteinValue: 10,
      carbohydratesValue: 52,
      fatValue: 14,
      fiberValue: 3,
      sodium: 580,
    },
    chiefTips: ["Keep the stock hot", "Use a heavy-bottomed pan"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 4100,
    cookTime: 15,
    prepTime: 10,
    servings: 4,
    level: "easy",
    type: "breakfast",
    title: "Fluffy Buttermilk Pancakes",
    description: "Soft and airy pancakes perfect for a weekend breakfast.",
    ingredients: ["Flour", "Buttermilk", "Eggs", "Baking powder", "Butter"],
    instructions: [
      "Mix dry ingredients",
      "Add wet ingredients",
      "Cook on griddle",
    ],
    nutrition: {
      caloriesValue: 310,
      proteinValue: 8,
      carbohydratesValue: 45,
      fatValue: 10,
      fiberValue: 1,
      sodium: 450,
    },
    chiefTips: ["Don't overmix the batter", "Flip when bubbles appear"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1300,
    cookTime: 10,
    prepTime: 10,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Garlic Shrimp Scampi",
    description: "Shrimp sautéed in a garlic, butter, and white wine sauce.",
    ingredients: ["Large shrimp", "Garlic", "Lemon", "Parsley", "Butter"],
    instructions: [
      "Sauté garlic",
      "Add shrimp",
      "Deglaze with wine/lemon",
      "Toss with parsley",
    ],
    nutrition: {
      caloriesValue: 280,
      proteinValue: 24,
      carbohydratesValue: 5,
      fatValue: 18,
      fiberValue: 0,
      sodium: 520,
    },
    chiefTips: ["Use wild-caught shrimp", "Serve over linguine"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 3800,
    cookTime: 60,
    prepTime: 30,
    servings: 6,
    level: "hard",
    type: "poultry",
    title: "Hyderabadi Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken.",
    ingredients: [
      "Basmati rice",
      "Chicken",
      "Yogurt",
      "Saffron",
      "Fried onions",
    ],
    instructions: [
      "Marinate chicken",
      "Parboil rice",
      "Layer chicken and rice",
      "Steam (Dum)",
    ],
    nutrition: {
      caloriesValue: 620,
      proteinValue: 38,
      carbohydratesValue: 75,
      fatValue: 18,
      fiberValue: 4,
      sodium: 900,
    },
    chiefTips: [
      "Use high-quality long grain rice",
      "Let it rest before opening",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&h=350&fit=crop",
    reviewRate: 4.5,
    reviewCount: 640,
    cookTime: 0,
    prepTime: 15,
    servings: 2,
    level: "easy",
    type: "salad",
    title: "Traditional Greek Salad",
    description: "Fresh cucumbers, tomatoes, olives, and feta cheese.",
    ingredients: [
      "Cucumber",
      "Tomato",
      "Kalamata olives",
      "Feta cheese",
      "Dried oregano",
    ],
    instructions: [
      "Chop vegetables",
      "Add olives and feta",
      "Drizzle with olive oil",
    ],
    nutrition: {
      caloriesValue: 210,
      proteinValue: 6,
      carbohydratesValue: 10,
      fatValue: 16,
      fiberValue: 3,
      sodium: 700,
    },
    chiefTips: [
      "Don't chop the feta, leave it in large blocks",
      "Use extra virgin olive oil",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1547641965-6f3b3da35c47?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 530,
    cookTime: 12,
    prepTime: 20,
    servings: 2,
    level: "medium",
    type: "meat",
    title: "Garlic Rosemary Lamb Chops",
    description: "Tender lamb chops infused with aromatic herbs.",
    ingredients: ["Lamb chops", "Rosemary", "Garlic", "Olive oil", "Butter"],
    instructions: ["Marinate lamb", "Sear in pan", "Baste with garlic butter"],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 32,
      carbohydratesValue: 2,
      fatValue: 35,
      fiberValue: 0,
      sodium: 380,
    },
    chiefTips: [
      "Bring meat to room temperature before cooking",
      "Sear the fat edge first",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=350&fit=crop",
    reviewRate: 4.3,
    reviewCount: 420,
    cookTime: 20,
    prepTime: 15,
    servings: 1,
    level: "easy",
    type: "vegetarian",
    title: "Buddha Quinoa Bowl",
    description: "A healthy mix of quinoa, roasted chickpeas, and tahini.",
    ingredients: [
      "Quinoa",
      "Chickpeas",
      "Spinach",
      "Sweet potato",
      "Tahini sauce",
    ],
    instructions: [
      "Cook quinoa",
      "Roast chickpeas",
      "Assemble bowl",
      "Drizzle sauce",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 14,
      carbohydratesValue: 55,
      fatValue: 12,
      fiberValue: 10,
      sodium: 290,
    },
    chiefTips: ["Massage the kale or spinach", "Meal prep this for lunch"],
  },
  {
    image:
      "https://images.unsplash.com/photo-1574894709923-1bc42b7b6f8c?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 2900,
    cookTime: 45,
    prepTime: 30,
    servings: 8,
    level: "hard",
    type: "meat",
    title: "Classic Beef Lasagna",
    description: "Layers of pasta, rich meat sauce, and creamy béchamel.",
    ingredients: [
      "Lasagna sheets",
      "Ground beef",
      "Tomato sauce",
      "Milk",
      "Cheese",
    ],
    instructions: [
      "Make meat sauce",
      "Make béchamel",
      "Layer ingredients",
      "Bake",
    ],
    nutrition: {
      caloriesValue: 520,
      proteinValue: 30,
      carbohydratesValue: 40,
      fatValue: 25,
      fiberValue: 2,
      sodium: 850,
    },
    chiefTips: [
      "Let it rest for 15 minutes before cutting",
      "Use mix of mozzarella and parmesan",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1581151927997-2d959118dde2?w=500&h=350&fit=crop",
    reviewRate: 4.6,
    reviewCount: 780,
    cookTime: 40,
    prepTime: 30,
    servings: 4,
    level: "medium",
    type: "vegetarian",
    title: "Eggplant Parmesan",
    description: "Baked eggplant slices layered with cheese and marinara.",
    ingredients: [
      "Eggplant",
      "Marinara sauce",
      "Mozzarella",
      "Breadcrumbs",
      "Egg",
    ],
    instructions: [
      "Bread eggplant",
      "Fry or bake",
      "Layer with sauce/cheese",
      "Bake again",
    ],
    nutrition: {
      caloriesValue: 340,
      proteinValue: 15,
      carbohydratesValue: 28,
      fatValue: 18,
      fiberValue: 7,
      sodium: 600,
    },
    chiefTips: [
      "Salt the eggplant to remove bitterness",
      "Don't use too much oil",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&h=350&fit=crop",
    reviewRate: 4.7,
    reviewCount: 1950,
    cookTime: 15,
    prepTime: 20,
    servings: 2,
    level: "medium",
    type: "seafood",
    title: "Authentic Shrimp Pad Thai",
    description: "Classic Thai stir-fried rice noodles with shrimp.",
    ingredients: [
      "Rice noodles",
      "Shrimp",
      "Tamarind paste",
      "Peanuts",
      "Bean sprouts",
    ],
    instructions: [
      "Soak noodles",
      "Stir-fry shrimp",
      "Add noodles and sauce",
      "Top with peanuts",
    ],
    nutrition: {
      caloriesValue: 490,
      proteinValue: 24,
      carbohydratesValue: 65,
      fatValue: 15,
      fiberValue: 4,
      sodium: 920,
    },
    chiefTips: [
      "Don't oversoak the noodles",
      "Use palm sugar for authenticity",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1562967914-608f82629710?w=500&h=350&fit=crop",
    reviewRate: 4.8,
    reviewCount: 3100,
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    level: "easy",
    type: "poultry",
    title: "Buffalo Chicken Wings",
    description: "Crispy fried wings tossed in spicy buffalo sauce.",
    ingredients: [
      "1kg Chicken wings",
      "Hot sauce",
      "Butter",
      "Garlic powder",
      "Flour",
    ],
    instructions: ["Coat wings in flour", "Fry until crispy", "Toss in sauce"],
    nutrition: {
      caloriesValue: 450,
      proteinValue: 22,
      carbohydratesValue: 5,
      fatValue: 38,
      fiberValue: 0,
      sodium: 1100,
    },
    chiefTips: [
      "Dry wings thoroughly for crispiness",
      "Use an air fryer for a healthier version",
    ],
  },
  {
    image:
      "https://images.unsplash.com/photo-1510618932816-ced4dc0b7302?w=500&h=350&fit=crop",
    reviewRate: 4.9,
    reviewCount: 1400,
    cookTime: 50,
    prepTime: 40,
    servings: 8,
    level: "hard",
    type: "dessert",
    title: "Classic Apple Pie",
    description: "A flaky buttery crust filled with spiced apples.",
    ingredients: ["Apples", "Pie crust", "Cinnamon", "Sugar", "Butter"],
    instructions: [
      "Make dough",
      "Prepare apple filling",
      "Assemble pie",
      "Bake",
    ],
    nutrition: {
      caloriesValue: 410,
      proteinValue: 3,
      carbohydratesValue: 58,
      fatValue: 19,
      fiberValue: 4,
      sodium: 300,
    },
    chiefTips: ["Use a mix of sweet and tart apples", "Keep dough cold"],
  },
  {
    image: "https://example.com/images/broken-link-margherita-pizza.jpg",
    reviewRate: 4.9,
    reviewCount: 3120,
    cookTime: 15,
    prepTime: 90,
    servings: 2,
    level: "medium",
    type: "vegetarian",
    title: "Italian Margherita Pizza",
    description: "Classic pizza with fresh mozzarella, tomatoes, and basil.",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Fresh mozzarella",
      "Basil leaves",
      "Olive oil",
    ],
    instructions: [
      "Roll out the dough",
      "Spread tomato sauce",
      "Add mozzarella slices",
      "Bake at 250°C",
      "Garnish with basil",
    ],
    nutrition: {
      caloriesValue: 580,
      proteinValue: 20,
      carbohydratesValue: 70,
      fatValue: 22,
      fiberValue: 4,
      sodium: 720,
    },
    chiefTips: ["Use a pizza stone", "Don't overload with toppings"],
  },
  {
    image: "https://myfakeapi.com/images/null/grilled-salmon.jpg",
    reviewRate: 4.7,
    reviewCount: 980,
    cookTime: 12,
    prepTime: 8,
    servings: 2,
    level: "easy",
    type: "seafood",
    title: "Lemon Butter Grilled Salmon",
    description: "Juicy salmon fillets with a rich lemon butter sauce.",
    ingredients: ["Salmon fillets", "Butter", "Lemon", "Garlic", "Parsley"],
    instructions: [
      "Season salmon",
      "Melt butter with garlic",
      "Grill salmon 6 minutes each side",
      "Drizzle lemon butter",
    ],
    nutrition: {
      caloriesValue: 420,
      proteinValue: 35,
      carbohydratesValue: 3,
      fatValue: 28,
      fiberValue: 0,
      sodium: 310,
    },
    chiefTips: ["Leave skin on for crispiness", "Don't overcook"],
  },
  {
    image: "broken-image-placeholder-404.webp",
    reviewRate: 4.6,
    reviewCount: 2450,
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    level: "medium",
    type: "poultry",
    title: "Creamy Garlic Chicken",
    description: "Tender chicken breasts in a creamy garlic parmesan sauce.",
    ingredients: [
      "Chicken breasts",
      "Heavy cream",
      "Parmesan",
      "Garlic",
      "Spinach",
    ],
    instructions: [
      "Sear chicken",
      "Sauté garlic",
      "Add cream and parmesan",
      "Simmer with spinach",
      "Return chicken to pan",
    ],
    nutrition: {
      caloriesValue: 540,
      proteinValue: 42,
      carbohydratesValue: 9,
      fatValue: 36,
      fiberValue: 1,
      sodium: 590,
    },
    chiefTips: ["Use freshly grated parmesan", "Don't boil the cream"],
  },
  {
    image: "https://notworking.com/img/beef-stew.jpg",
    reviewRate: 4.8,
    reviewCount: 1870,
    cookTime: 110,
    prepTime: 20,
    servings: 6,
    level: "medium",
    type: "meat",
    title: "Hearty Beef Stew",
    description: "Slow-cooked beef with potatoes and carrots in rich gravy.",
    ingredients: ["Beef chuck", "Potatoes", "Carrots", "Onion", "Beef broth"],
    instructions: [
      "Sear beef until brown",
      "Add vegetables",
      "Pour broth",
      "Simmer for 1.5 hours",
      "Season to taste",
    ],
    nutrition: {
      caloriesValue: 490,
      proteinValue: 38,
      carbohydratesValue: 32,
      fatValue: 22,
      fiberValue: 5,
      sodium: 810,
    },
    chiefTips: ["Sear meat in batches", "Let it rest before serving"],
  },
  {
    image: "/images/404-not-found-pasta.jpg",
    reviewRate: 4.5,
    reviewCount: 1430,
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    level: "easy",
    type: "vegetarian",
    title: "Tomato Basil Pasta",
    description: "Simple and fresh pasta with cherry tomatoes and basil.",
    ingredients: [
      "Spaghetti",
      "Cherry tomatoes",
      "Fresh basil",
      "Garlic",
      "Olive oil",
    ],
    instructions: [
      "Cook pasta",
      "Sauté garlic and tomatoes",
      "Mix with pasta",
      "Add fresh basil",
    ],
    nutrition: {
      caloriesValue: 470,
      proteinValue: 12,
      carbohydratesValue: 68,
      fatValue: 16,
      fiberValue: 5,
      sodium: 210,
    },
    chiefTips: ["Save pasta water", "Use ripe tomatoes"],
  },
  {
    image: "https://fakestorage.com/recipes/empty/tacos.jpg",
    reviewRate: 4.9,
    reviewCount: 2950,
    cookTime: 15,
    prepTime: 15,
    servings: 4,
    level: "easy",
    type: "meat",
    title: "Street Style Beef Tacos",
    description: "Authentic Mexican tacos with seasoned beef and fresh salsa.",
    ingredients: ["Ground beef", "Corn tortillas", "Onion", "Cilantro", "Lime"],
    instructions: [
      "Cook beef with spices",
      "Warm tortillas",
      "Fill tortillas",
      "Top with onion and cilantro",
    ],
    nutrition: {
      caloriesValue: 380,
      proteinValue: 22,
      carbohydratesValue: 28,
      fatValue: 19,
      fiberValue: 3,
      sodium: 520,
    },
    chiefTips: ["Double stack tortillas", "Serve with lime wedges"],
  },
  {
    image: "error-404-image-not-available.png",
    reviewRate: 4.7,
    reviewCount: 760,
    cookTime: 25,
    prepTime: 10,
    servings: 2,
    level: "medium",
    type: "seafood",
    title: "Garlic Butter Shrimp",
    description: "Succulent shrimp in a rich garlic butter sauce.",
    ingredients: [
      "Large shrimp",
      "Butter",
      "Garlic",
      "Lemon juice",
      "Red pepper flakes",
    ],
    instructions: [
      "Melt butter",
      "Sauté garlic",
      "Add shrimp",
      "Cook 2-3 minutes",
      "Add lemon and pepper flakes",
    ],
    nutrition: {
      caloriesValue: 340,
      proteinValue: 28,
      carbohydratesValue: 4,
      fatValue: 23,
      fiberValue: 0,
      sodium: 640,
    },
    chiefTips: ["Don't overcook shrimp", "Serve with crusty bread"],
  },
  {
    image: "https://invalid.link/mushroom-risotto.jpg",
    reviewRate: 4.6,
    reviewCount: 1120,
    cookTime: 35,
    prepTime: 10,
    servings: 4,
    level: "hard",
    type: "vegetarian",
    title: "Wild Mushroom Risotto",
    description: "Creamy Italian rice with earthy wild mushrooms.",
    ingredients: [
      "Arborio rice",
      "Wild mushrooms",
      "Vegetable stock",
      "White wine",
      "Parmesan",
    ],
    instructions: [
      "Sauté mushrooms",
      "Toast rice",
      "Add wine",
      "Add stock gradually",
      "Stir constantly",
    ],
    nutrition: {
      caloriesValue: 440,
      proteinValue: 12,
      carbohydratesValue: 58,
      fatValue: 17,
      fiberValue: 3,
      sodium: 480,
    },
    chiefTips: ["Keep stock warm", "Stir, stir, stir"],
  },
  {
    image: "null-image-broken-link.jpg",
    reviewRate: 4.8,
    reviewCount: 2100,
    cookTime: 40,
    prepTime: 25,
    servings: 6,
    level: "hard",
    type: "meat",
    title: "Classic Beef Lasagna",
    description: "Layers of pasta, meat sauce, and creamy béchamel.",
    ingredients: [
      "Lasagna sheets",
      "Ground beef",
      "Tomato sauce",
      "Béchamel",
      "Mozzarella",
    ],
    instructions: [
      "Make meat sauce",
      "Prepare béchamel",
      "Layer pasta, sauce, cheese",
      "Bake at 180°C for 40 minutes",
    ],
    nutrition: {
      caloriesValue: 610,
      proteinValue: 35,
      carbohydratesValue: 45,
      fatValue: 32,
      fiberValue: 4,
      sodium: 890,
    },
    chiefTips: ["Let rest 15 minutes before cutting", "Use no-boil noodles"],
  },
  {
    image: "https://example.com/404/avocado-toast.jpg",
    reviewRate: 4.4,
    reviewCount: 830,
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    level: "easy",
    type: "breakfast",
    title: "Avocado & Egg Toast",
    description: "Creamy avocado toast topped with a poached egg.",
    ingredients: [
      "Sourdough bread",
      "Avocado",
      "Egg",
      "Red pepper flakes",
      "Lemon juice",
    ],
    instructions: [
      "Toast bread",
      "Mash avocado",
      "Poach egg",
      "Assemble",
      "Season with pepper flakes",
    ],
    nutrition: {
      caloriesValue: 350,
      proteinValue: 14,
      carbohydratesValue: 28,
      fatValue: 21,
      fiberValue: 9,
      sodium: 290,
    },
    chiefTips: ["Use ripe avocado", "Add everything bagel seasoning"],
  },
];
